routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');

Route::view('dashboard', 'dashboard')
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::view('profile', 'profile')
    ->middleware(['auth'])
    ->name('profile');

// Tests
Route::prefix('tests')->name('test.')->middleware(['auth', 'verified'])->group(function () {
    Route::get('create', [TestController::class, 'create'])
        ->name('create');
    Route::get('list', [TestController::class, 'list'])
        ->name('list');
    Route::get('show/{test}', [TestController::class, 'show'])
        ->name('show');
    Route::get('edit/{test}', [TestController::class, 'edit'])
        ->name('edit');
    Route::delete('destroy/{test}', [TestController::class, 'destroy'])
        ->name('destroy');
});

// Categories
Route::prefix('categories')->name('category.')->middleware(['auth', 'verified', 'is_admin'])->group(function () {
    Route::get('create', [CategoryController::class, 'create'])
        ->name('create');
    Route::get('list', [CategoryController::class, 'list'])
        ->name('list');
    Route::get('show/{category}', [CategoryController::class, 'show'])
        ->name('show');
    Route::get('edit/{category}', [CategoryController::class, 'edit'])
        ->name('edit');
    Route::delete('destroy/{category}', [CategoryController::class, 'destroy'])
        ->name('destroy');
});

// PDF
Route::prefix('pdf')->name('pdf.')->middleware(['auth', 'verified', 'tests_completed'])->group(function () {
    Route::get('generate', [PdfController::class, 'generate'])
        ->name('generate');
});

require __DIR__.'/auth.php';

app/Livewire/Actions/Logout.php
<?php

namespace App\Livewire\Actions;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class Logout
{
    /**
     * Log the current user out of the application.
     */
    public function __invoke(): void
    {
        Auth::guard('web')->logout();

        Session::invalidate();
        Session::regenerateToken();
    }
}

app/Livewire/Dashboard/PatientInformations.php
<?php

namespace App\Livewire\Dashboard;

use Livewire\Attributes\On;
use Livewire\Attributes\Session;
use Livewire\Component;

class PatientInformations extends Component
{
    #[Session(key: 'patient.informations')]
    public array $patientInformations;

    public function openModal()
    {
        $this->dispatch('open-modal-patient', $this->patientInformations ?? null);
    }

    #[On('clear-patient-informations')]
    public function clearPatientInformations()
    {
        $this->patientInformations = [];
    }

    #[On('close-modal-patient')]
    public function closeModal()
    {
        $this->patientInformations = session('patient.informations');
    }

    #[On('check-patient-informations')]
    public function checkPatientInformations(): void
    {
        if (empty($this->patientInformations)) {
            $this->dispatch('notify',
                ['message' => trans('messages.patient_missing_infos'), 'type' => 'warning']
            );
        }
    }

    public function render()
    {
        return view('livewire.dashboard.patient-informations');
    }
}

app/Livewire/Dashboard/PatientTests.php
<?php

namespace App\Livewire\Dashboard;

use App\Models\Test;
use Livewire\Attributes\Locked;
use Livewire\Attributes\On;
use Livewire\Attributes\Session;
use Livewire\Component;

class PatientTests extends Component
{
    #[Session(key: 'patient.testsList')]
    public array $patientTestsList;

    #[Locked]
    public bool $patientProfileCompleted = false;

    #[On('clear-patient-informations')]
    public function patientProfileCompletedEmpty()
    {
        $this->patientProfileCompleted = false;
    }

    public function mount(): void
    {
        if (session()->has('patient.informations') && ! empty(session('patient.informations'))) {
            $this->patientProfileCompleted = true;
        }
    }

    #[On('close-modal-patient')]
    public function patientProfileCompletedSuccess()
    {
        $this->patientProfileCompleted = true;
    }

    public function loadNewItem($itemId): void
    {

        $item = Test::find($itemId, ['name']);

        if (! $item) {

            $this->dispatch('notify',
                ['message' => trans('messages.unable_to_find_test'), 'type' => 'danger']
            );

            return;

        }

        $testName = $item->name;

        $componentName = 'TestsPatient.'.ucfirst($testName);
        $componentPath = app_path('Livewire/'.str_replace('.', '/', $componentName).'.php');

        if (! file_exists($componentPath)) {
            $this->dispatch('notify',
                [
                    'message' => trans_choice('messages.unable_to_load_file', 1, ['value' => $testName]),
                    'type' => 'danger',
                ]
            );

            return;
        }

        $uuid = uniqid('item_');
        $this->patientTestsList[] = [
            'id' => $itemId,
            'uuid' => $uuid,
            'position' => collect($this->patientTestsList)->count(),
            'name' => $testName,
            'is_completed' => false,
            'data' => [
                'form' => [],
                'result' => [],
            ],
        ];

        session(['patient.testsList' => $this->patientTestsList]);

        $this->dispatch('add-item', [$uuid]);

    }

    #[On('updated-testList')]
    public function updatedTestList($test): void
    {
        $this->patientTestsList = collect($this->patientTestsList)
            ->map(function ($item) use ($test) {
                if ($item['uuid'] === $test['uuid']) {
                    $item['data'] = $test['data'];
                    $item['is_completed'] = $test['is_completed'];
                }

                return $item;
            })
            ->toArray();
        session(['patient.testsList' => $this->patientTestsList]);
    }

    public function sortItem($item, $newPosition): void
    {
        $currentPosition = collect($this->patientTestsList)->firstWhere('uuid', $item)['position'];
        $this->patientTestsList = collect(session('patient.testsList'))
            ->map(function ($test) use ($currentPosition, $newPosition, $item) {
                if ($test['uuid'] === $item) {
                    $test['position'] = $newPosition;
                } elseif ($test['position'] >= min($currentPosition,
                    $newPosition) && $test['position'] <= max($currentPosition, $newPosition)) {
                    $test['position'] += ($currentPosition < $newPosition) ? -1 : 1;
                }

                return $test;
            })
            ->sortBy('position')
            ->values()
            ->toArray();
        session(['patient.testsList' => $this->patientTestsList]);
    }

    public function removeItem($uuid): void
    {

        $currentPosition = collect($this->patientTestsList)->firstWhere('uuid', $uuid)['position'];

        $this->patientTestsList = collect(session('patient.testsList'))
            ->map(function ($test) use ($currentPosition, $uuid) {
                if ($test['uuid'] === $uuid) {
                    return null;
                }
                if ($test['position'] > $currentPosition) {
                    $test['position'] -= 1;
                }

                return $test;
            })
            ->filter()
            ->values()
            ->toArray();
        session(['patient.testsList' => $this->patientTestsList]);
        $this->dispatch('remove-item', [$uuid]);

    }

    public function checkPatientTestsCompleted(): bool
    {

        $incompleteTests = collect($this->patientTestsList)->where('is_completed', false);

        if (! $this->patientProfileCompleted) {

            $this->dispatch('notify',
                ['message' => trans('messages.patient_missing_infos'), 'type' => 'warning']
            );

            return false;
        }

        if (collect($this->patientTestsList)->count() === 0) {

            $this->dispatch('notify',
                ['message' => trans('messages.no_test_selected'), 'type' => 'warning']

            );

            return false;

        } elseif ($incompleteTests->count() > 0) {

            $errors = $incompleteTests->map(function ($test) {
                return $test['name'];
            });

            $this->dispatch('notify',
                [
                    'message' => trans_choice('messages.test_validation_failed', $incompleteTests->count(),
                        ['values' => $errors->implode(', ')]), 'type' => 'warning',
                ]
            );

            return false;

        }

        return true;

    }

    public function submitItems(): void
    {

        if (! $this->checkPatientTestsCompleted()) {
            return;
        }

        dd('All tests are completed');

    }

    public function render()
    {
        return view('livewire.dashboard.patient-tests');
    }
}

app/Livewire/Editor/Quill.php
<?php

namespace App\Livewire\Editor;

use App\Models\Test;
use Livewire\Attributes\On;
use Livewire\Component;

class Quill extends Component
{
    public string $content;

    public string $quillId;

    public string $quillReadOnly;

    public string $quillToolBar;

    public function mount($quillReadOnly = 'false', $content = null)
    {
        $this->quillReadOnly = $quillReadOnly;
        $this->quillToolBar = $this->quillReadOnly === 'true' ? 'false' : 'true';
        $this->quillId = 'quill-'.uniqid();

        if ($content) {
            $this->content = $content;
        }
    }

    #[On('load-item-description')]
    public function loadItemDescription($data): void
    {
        $item = Test::find($data['id'], ['content']);

        if (! $item) {

            $this->dispatch('notify',
                ['message' => trans('messages.unable_to_find_test'), 'type' => 'danger']
            );

            return;

        }

        $this->content = $item->content;
        $this->dispatch('quill-content-update', [$this->content]);
    }

    public function updatedContent($content)
    {
        $this->dispatch('quill-content-update', $content);
        // $this->content = $content;
    }

    public function render()
    {
        return view('livewire.editor.quill');
    }
}

app/Livewire/Forms/LoginForm.php
<?php

namespace App\Livewire\Forms;

use Illuminate\Auth\Events\Lockout;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Livewire\Attributes\Validate;
use Livewire\Form;

class LoginForm extends Form
{
    #[Validate('required|string|email')]
    public string $email = '';

    #[Validate('required|string')]
    public string $password = '';

    #[Validate('boolean')]
    public bool $remember = false;

    /**
     * Attempt to authenticate the request's credentials.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function authenticate(): void
    {
        $this->ensureIsNotRateLimited();

        if (! Auth::attempt($this->only(['email', 'password']), $this->remember)) {
            RateLimiter::hit($this->throttleKey());

            throw ValidationException::withMessages([
                'form.email' => trans('auth.failed'),
            ]);
        }

        RateLimiter::clear($this->throttleKey());
    }

    /**
     * Ensure the authentication request is not rate limited.
     */
    protected function ensureIsNotRateLimited(): void
    {
        if (! RateLimiter::tooManyAttempts($this->throttleKey(), 5)) {
            return;
        }

        event(new Lockout(request()));

        $seconds = RateLimiter::availableIn($this->throttleKey());

        throw ValidationException::withMessages([
            'form.email' => trans('auth.throttle', [
                'seconds' => $seconds,
                'minutes' => ceil($seconds / 60),
            ]),
        ]);
    }

    /**
     * Get the authentication rate limiting throttle key.
     */
    protected function throttleKey(): string
    {
        return Str::transliterate(Str::lower($this->email).'|'.request()->ip());
    }
}

app/Livewire/Forms/PatientForm.php
<?php

namespace App\Livewire\Forms;

use Illuminate\Validation\Rule;
use Livewire\Form;

class PatientForm extends Form
{
    public string $name = '';

    public string $username = '';

    public string $birthdate = '';

    public string $job = '';

    public array $school_grade_options = [
        '1',
        '2',
        '3',
    ];

    public string $school_grade = '';

    public array $gender_options = [
        'male',
        'female',
    ];

    public string $gender = '';

    public string $date = '';

    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'username' => ['required', 'string', 'min:1', 'max:255'],
            'birthdate' => ['required', 'date', 'date_format:"Y-m-d"'],
            'job' => ['required', 'string', 'max:255'],
            'date' => ['required', 'date', 'date_format:"Y-m-d"'],
            'gender' => ['required', 'string', Rule::in($this->gender_options)],
            'school_grade' => ['required', 'string', Rule::in($this->school_grade_options)],
        ];
    }
}

app/Livewire/Forms/TestsPatient/RlriForm.php
<?php

namespace App\Livewire\Forms\TestsPatient;

use Livewire\Form;

class RlriForm extends Form
{
    public string $username = 'toto';

    public string $password = '1234';

    public int $value = 0;

    public function rules(): array
    {
        return [
            'email' => 'required|string|email',
        ];
    }
}

app/Livewire/Forms/TestsPatientProcedures/EditCategoryForm.php
<?php

namespace App\Livewire\Forms\TestsPatientProcedures;

use Livewire\Form;

class EditCategoryForm extends Form
{
    public string $name = '';

    public string $slug = '';

    public int $id = 0;

    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255', 'unique:categories,name,'.$this->id],
            'slug' => ['required', 'string', 'max:255'],
        ];
    }
}

app/Livewire/Forms/TestsPatientProcedures/EditProcedureForm.php
<?php

namespace App\Livewire\Forms\TestsPatientProcedures;

use Livewire\Form;

class EditProcedureForm extends Form
{
    public string $name = '';

    public string $slug = '';

    public string $versions = '';

    public string $content = '';

    public bool $is_active = true;

    public int $id = 0;

    public array $categories = [];

    public array $users = [];

    public function rules(): array
    {
        return [
            'categories' => ['required', 'array', 'min:1'],
            'users' => ['required', 'array', 'min:1'],
            'name' => ['required', 'string', 'max:255', 'unique:tests,name,'.$this->id],
            'slug' => ['required', 'string', 'max:255'],
            // 'versions' => ['required', 'string', 'regex:/^\["[^"]*"(?:,"[^"]*")*\]$/'],
            'versions' => ['required', 'string', 'regex:/^\[(?:"[^"]*"(?:,"[^"]*")*)?\]$/'],
            'content' => ['nullable', 'string'],
            'is_active' => ['boolean'],
        ];
    }
}

app/Livewire/Modals/Patient.php
<?php

namespace App\Livewire\Modals;

use App\Livewire\Forms\PatientForm;
use Livewire\Attributes\On;
use Livewire\Component;

class Patient extends Component
{
    public PatientForm $form;

    public bool $isOpen = false;

    #[On('open-modal-patient')]
    public function openModal($data = null)
    {

        if ($data) {
            $this->form->fill($data);
        }

        $this->isOpen = true;
    }

    public function save()
    {
        $this->form->date = now()->format('Y-m-d');
        $this->validate();
        $data = $this->form->except('gender_options', 'school_grade_options');
        $this->store($data);
        $this->dispatch('close-modal-patient');
        $this->dispatch('notify',
            ['message' => trans('messages.modal_patient_info_added'), 'type' => 'success']
        );
        $this->form->reset();
    }

    public function store($data)
    {

        if (session()->has('patient.informations')) {
            session()->forget('patient.informations');
        }

        session()->put('patient.informations', $data);
        $this->isOpen = false;

    }

    public function clearForm()
    {
        if (session()->has('patient.informations')) {
            session()->forget('patient.informations');
        }
        $this->form->reset();
        $this->dispatch('clear-patient-informations');
    }

    public function render()
    {
        return view('livewire.modals.patient');
    }
}

app/Livewire/TestsPatientProcedures/UserList.php
<?php

namespace App\Livewire\TestsPatientProcedures;

use Illuminate\Support\Facades\Auth;
use Livewire\Component;
use Livewire\WithPagination;

class UserList extends Component
{
    use withPagination;

    protected int $paginate = 8;

    public function paginationView()
    {
        return 'livewire.components.pagination';
    }

    public function render()
    {

        $tests = Auth::user()
            ->tests()
            ->with('categories')
            ->orderBy('name', 'asc')
            ->paginate($this->paginate);

        // Get the collection from the paginator
        $collection = $tests->getCollection();
        $tests->setCollection($collection);

        return view('livewire.tests-patient-procedures.user-list', [
            'tests' => $tests,
        ]);
    }
}

resources/views/livewire/tests-patient-categories/user-list-edit.blade.php
<div class="{{!$displayTable ? 'column is-12' : ''}}">
    <form
        wire:submit="save" @class(['box' => !$displayTable, 'column'])>
        <div @class(['m-4' => !$displayTable, 'p-4' => !$displayTable, 'my-4' => $displayTable, 'field', 'is-horizontal'])">
            <x-input-label class="is-pulled-right" for="name" :value="__('messages.name')"/>
            <div class="field-body">
                <div class="field">
                    <div class="control has-icons-left">
                        <input class="input" type="text" wire:model="form.name">
                        <x-input-icon class="icon is-small is-left" icon="description"/>
                        <x-input-error :messages="$errors->get('form.name')" class="mt-2"/>
                    </div>
                </div>
                <div class="field">
                    <p class="control">
                        <button class="button is-link">{{ __('messages.save') }}</button>
                    </p>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/livewire/tests-patient-categories/user-list.blade.php
<div class="container" x-data="{selection: $wire.entangle('selection')}">
    <div class="columns is-align-items-center is-multiline is-mobile">
        <div class="column is-full">
            <x-link-button
                wire:navigate
                href="{{ route('category.create') }}">
                {{ __('messages.category_create') }}
            </x-link-button>
        </div>
        <div class="column is-full">
            <div class="is-flex is-justify-content-center">
                <label for="search_ingredient"
                       class="is-size-4 has-text-weight-semibold">{{__('messages.category_search')}}</label>
            </div>
            <div class="column is-one-third-desktop is-half-tablet mx-auto px-0">
                <div id="tableSearchActivities"
                     class="tableSearch control field mb-5 mx-auto has-icons-left">
                    <x-input-text
                        wire:model.live.debounce.250ms="search"
                        id="search_category"
                        class="input is-half-desktop"
                        name="search_category"
                        type="text"
                    />
                    <x-input-icon class="icon is-small is-left" icon="search"/>
                </div>
            </div>
            <x-danger-button
                class="button is-danger is-light my-4"
                x-cloak
                x-show="selection.length > 0"
                x-on:click="$wire.deleteSelected">
                <span class="material-symbols-outlined mr-2">delete</span>
                <span>{{ __('messages.delete') }}</span>
            </x-danger-button>
            <div class="table-container">
                <table class="table is-fullwidth is-hoverable">
                    <thead>
                    <tr>
                        <th>{{__('messages.select')}}</th>
                        <x-table-header name="name" :direction="$orderDirection" :field="$orderField">
                            {{__('messages.name')}}
                        </x-table-header>
                        <th>{{__('messages.edit')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>
                                <div class="field ml-2">
                                    <label class="b-checkbox checkbox">
                                        <input id="checkbox-{{$category->id}}"
                                               class="is-checkradio is-circle"
                                               x-model="selection"
                                               value="{{$category->id}}"
                                               type="checkbox"
                                               name="checkbox-{{$category->id}}">
                                        <span class="check is-link"></span>
                                    </label>
                                </div>
                            </td>
                            <td>{{ $category->name }}</td>
                            <td>
                                <button
                                    class="button is-link is-light"
                                    :class="{'is-dark': sessionStorage.getItem('darkMode') === 'true' }"
                                    wire:click="startEdit({{$category->id}})">
                                    <span class="material-symbols-outlined">edit</span>
                                </button>
                            </td>
                        </tr>
                        @if($editId === $category->id)
                            <tr class="is-active">
                                <td colspan="3">
                                    <livewire:tests-patient-categories.user-list-edit
                                        :displayTable="true"
                                        :edit="false"
                                        :category="$category"
                                        :key="$category->id"/>
                                </td>
                            </tr>
                    @endif
                    @endforeach
                </table>
            </div>
            {{$categories->links()}}
        </div>
    </div>
</div>